# Generated by Django 2.2.7 on 2019-11-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atkn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
