# Generated by Django 2.2.4 on 2019-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atkn', '0005_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='image',
            name='videofile',
        ),
        migrations.AddField(
            model_name='image',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
